[build]
  command = "npm run build"
  publish = "dist"          # Carpeta donde se genera el build
  functions = "netlify/functions"  # Opcional para funciones serverless

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200